# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install any needed packages
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Make port 4444 available to the world outside this container
EXPOSE 4444

# Define environment variable
ENV NODE_ENV=production

# Run the app
CMD [ "node", "./api/server.js" ]
